### ISSUE TITLE
Missing owner in the license file

### ISSUE THREAD

**Issue by mportuga** [darsain/remove-trailing-separator#5]
Can you add an owner to your license

**Comment by darsain** [comment]
Is it necessary? Is it invalid if it's missing?

**Comment by phated** [comment]
I was once told it must have a legal entity as the owner, like a person or business.  e.g. it can't be a screen name.

**Comment by darsain** [comment]
1. Does it also has to have a year? Hope not, that's one super annoying thing to maintain :/
2. Do I have to publish this to npm or is it enough here on github? Wouldn't want to cause an unnecessary patch update to so many people just because of this.

**Comment by phated** [comment]
1. I believe it's supposed to have a year but it's only supposed to reflect the years in which the code is written or changed.  So if this module is "done", you'd never need to update it.
2. A copy of the license is supposed to ship with the software, but npm has always played fast-and-loose with that because they inline SPDX into the package.json.  You could probably get away with not publishing it until the next version that needs to be released.

**Comment by darsain** [comment]
Owner and year added, nothing to publish to npm though, so skipping that.
